-- Quaisquer registros que devem ser inseridos no banco de dados durante a instalação da aplicação devem ser colocados aqui

-- Livros

INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (10, 2005, 'Bruna Surfistinha', 1, 'Panda Books', 60, 'Biografia', '9788576950172', 27.10, 'Neste livro você vai conhecer detalhes reveladores da menina de classe média alta que trocou os finais de semana com a família no Guarujá para se prostituir aos 17 anos.', 'O Doce Veneno do Escorpião');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (9, 2007, 'Mario Puzo', 1, 'Bestbolso', 2, 'Romance', '8577990192', 25, 'A mais perfeita reconstituição da Cosa Nostra, a Máfia americana, e do mundo alucinante criado por cinco famílias do mafiosi em guerra em Nova York.', 'O Poderoso Chefão');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (8, 2004, 'Dan Brown', 1, 'Arqueiro', 1, 'Romance', '8575421468', 23.90, 'Antes de decifrar O Código Da Vinci, Robert Langdon, o famoso professor de simbologia de Harvard, vive sua primeira aventura em Anjos e Demônios, quando tenta impedir que uma antiga sociedade secreta destrua a Cidade do Vaticano.', 'Anjos e Demônios');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (7, 2004, 'Dan Brown', 1, 'Arqueiro', 20, 'Romance', '8575421131', 23.90, 'Um assassinato dentro do Museu do Louvre, em Paris, traz à tona uma sinistra conspiração para revelar um segredo que foi protegido por uma sociedade secreta desde os tempos de Jesus Cristo.' , 'O Código da Vinci');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (6, 2013, 'Dan Brown', 1, 'Arqueiro', 20, 'Romance', '9788580411522', 39.90, 'Neste novo e fascinante thriller Dan Brown retoma a mistura magistral de história, arte, códigos e símbolos que o consagrou em O código Da Vinci, Anjos e demônios e O símbolo perdido e faz de Inferno sua aposta mais alta até o momento.', 'Inferno');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (5, 2006, 'Deitel', 5, 'Prentice Hall', 10, 'Informática', '8576050560', 410, 'A melhor e mais respeitada introdução a C++, programação orientada a objetos (POO) e projeto orientado a objetos (OOD) com UML 2 utilizando o Deitel Live-Code.', 'C ++ Como Programar');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (4, 2011, 'Andrew S. Tanenbaum', 5, 'Pearson Education', 50, 'Informática', '9788576059240', 170, 'Este livro aborda as redes desenvolvidas a partir de 1990, explicando com elas funcionam internamente. Andrew Tanenbaum apresenta explicações detalhadas e exemplos baseados na Internet para facilitar a compreensão do leitor.', 'Redes de Computadores');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (3, 2005, 'Sierra Kathy', 1, 'Alta Books', 5, 'Informática', '9788576081739', 139, 'Use a Cabeça Java é uma experiência completa de aprendizado em programação orientada a objetos (OO) e Java.', 'Use a Cabeça Java');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (2, 2013, 'Ricardo Lecheta', 3, 'Novatec', 30, 'Informática', '9788575223444', 123, 'O Android é a plataforma open-source criada pelo Google para o desenvolvimento de aplicações para dispositivos móveis. É a nova sensação do momento e está revolucionando o desenvolvimento de aplicações.', 'Google Android');
INSERT INTO livro (id, ano, autor, edicao, editora, estoque, genero, isbn, preco, sinopse, titulo) VALUES (1, 2010, 'Deitel', 8, 'Prentice Hall', 10, 'Informática', '9788576055631', 312, 'A oitava edição de Java - como programar, lançada pela Pearson Education, chega ao mercado com novo design e um traço inovador.', 'Java - Como Programar');
